name: Cookie Consent
version: "1.0"
description: Make your website comply with the crazy EU cookie law
url: https://github.com/marbles/Cookie Consent
developer: Marbles
developer_url: https://www.marbles.be
